/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedirectRouteImport } from './routes/redirect'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DoorUidOpenRouteImport } from './routes/door.$uid.open'
import { ServerRoute as ApiDoorUidOpenServerRouteImport } from './routes/api/door.$uid.open'

const rootServerRouteImport = createServerRootRoute()

const RedirectRoute = RedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoorUidOpenRoute = DoorUidOpenRouteImport.update({
  id: '/door/$uid/open',
  path: '/door/$uid/open',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDoorUidOpenServerRoute = ApiDoorUidOpenServerRouteImport.update({
  id: '/api/door/$uid/open',
  path: '/api/door/$uid/open',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/redirect': typeof RedirectRoute
  '/door/$uid/open': typeof DoorUidOpenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/redirect': typeof RedirectRoute
  '/door/$uid/open': typeof DoorUidOpenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/redirect': typeof RedirectRoute
  '/door/$uid/open': typeof DoorUidOpenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/redirect' | '/door/$uid/open'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/redirect' | '/door/$uid/open'
  id: '__root__' | '/' | '/redirect' | '/door/$uid/open'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RedirectRoute: typeof RedirectRoute
  DoorUidOpenRoute: typeof DoorUidOpenRoute
}
export interface FileServerRoutesByFullPath {
  '/api/door/$uid/open': typeof ApiDoorUidOpenServerRoute
}
export interface FileServerRoutesByTo {
  '/api/door/$uid/open': typeof ApiDoorUidOpenServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/door/$uid/open': typeof ApiDoorUidOpenServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/door/$uid/open'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/door/$uid/open'
  id: '__root__' | '/api/door/$uid/open'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiDoorUidOpenServerRoute: typeof ApiDoorUidOpenServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/door/$uid/open': {
      id: '/door/$uid/open'
      path: '/door/$uid/open'
      fullPath: '/door/$uid/open'
      preLoaderRoute: typeof DoorUidOpenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/door/$uid/open': {
      id: '/api/door/$uid/open'
      path: '/api/door/$uid/open'
      fullPath: '/api/door/$uid/open'
      preLoaderRoute: typeof ApiDoorUidOpenServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RedirectRoute: RedirectRoute,
  DoorUidOpenRoute: DoorUidOpenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiDoorUidOpenServerRoute: ApiDoorUidOpenServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
